apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iagfzyxmg-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/iagfzyxmg-nodejs-gitops